apiVersion: v1
kind: Service
metadata:
  name: praksa-api-service
spec:
  selector:
    app: praksa-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
  type: NodePort
